### ISSUE TITLE
ValueError: mutable default <class 'cyberbattle.simulation.model.FirewallConfiguration'> for field firewall is not allowed: use default_factory

### ISSUE THREAD

**Issue by virenderdhiman** [microsoft/CyberBattleSim#112] opened 2023-10-10 02:17 UTC
I am getting the  issue when I try to clone and run the test with following command "python -m cyberbattle.agents.baseline.run --training_episode_count 5 --eval_episode_count 3 --iteration_count 100 --rewardplot_width 80 --chain_size=4 --ownership_goal 0.2
Issue:

File "/home/landon/miniconda3/envs/cybersim/lib/python3.11/dataclasses.py", line 815, in _get_field
raise ValueError(f'mutable default {type(f.default)} for field '
ValueError: mutable default <class 'cyberbattle.simulation.model.FirewallConfiguration'> for field firewall is not allowed: use default_factory

Can someone provide the resolution for this?

**Comment by IpadLi** [comment] 2023-10-13 03:22
I have the same issue.

**Comment by blumu** [comment] 2023-10-13 16:58
Quick fix is to patch the env.yaml file to use python=3.9 instead of `>=3.9`. Fixed in PR #113

**Comment by blumu** [comment] 2023-10-13 20:28
Duplicate of #111

**Closed by blumu** 2023-10-13 20:28 UTC
Labels: bug
