### ISSUE TITLE
Dockerfile not working

### ISSUE THREAD

**Issue by Zone04** [microsoft/CyberBattleSim#100] opened 2023-02-17 17:04 UTC
Hello,

Just letting you know that building the container using the included Dockerfile does not work starting from commit 9b4d29418a4b5a37117132f3e6ea7d93b43b72fe from September 22nd 2022 updating to python 3.9.
Previous commit c289695 "CI Fixes, requires networkx upgrade to 2.8.6 (#85)" does work.

**Comment by blumu** [comment] 2023-02-18 19:22
@Zone04 Could you share the error message you are getting? The docker build succeeded when the commit was merged last month. I am wondering if your error is caused by a broken dependency.
https://github.com/microsoft/CyberBattleSim/actions/runs/3834494741/jobs/6526950954

**Comment by blumu** [comment] 2023-02-18 19:55
I could repro the following error which seems related to https://github.com/freqtrade/freqtrade/issues/8078
```
#0 131.7 Collecting gym==0.21.0
#0 131.8   Downloading gym-0.21.0.tar.gz (1.5 MB)
#0 131.9      ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 15.3 MB/s eta 0:00:00
#0 132.0   Preparing metadata (setup.py): started
#0 132.1   Preparing metadata (setup.py): finished with status 'error'
#0 132.1   error: subprocess-exited-with-error
#0 132.1
#0 132.1   × python setup.py egg_info did not run successfully.
#0 132.1   │ exit code: 1
#0 132.1   ╰─> [1 lines of output]
#0 132.1       error in gym setup command: 'extras_require' must be a dictionary whose values are strings or lists of strings containing valid project/version requirement specifiers.
#0 132.1       [end of output]
#0 132.1
#0 132.1   note: This error originates from a subprocess, and is likely not a problem with pip.
#0 132.1 error: metadata-generation-failed
#0 132.1
#0 132.1 × Encountered error while generating package metadata.
#0 132.1 ╰─> See above for output.
#0 132.1
#0 132.1 note: This is an issue with the package mentioned above, not pip.
#0 132.1 hint: See above for details.
#0 132.2 + echo 'An error occured when installing package dependencies'
#0 132.2 + exit 1
#0 132.2 An error occured when installing package dependencies
```

**Comment by blumu** [comment] 2023-02-18 20:11
@zone04 If it's the same error you are hitting then this PR fixes the problem: https://github.com/microsoft/CyberBattleSim/pull/101
Let me know if this is not the case. Thanks!

**Comment by Zone04** [comment] 2023-02-18 20:43
Hello, this was indeed the exact error I encountered. I will try the PR on Monday and let you know if everything went right.
Thanks!

**Comment by Zone04** [comment] 2023-02-20 09:09
I confirm that everything works as intended with this PR

**Closed** 2023-02-20 09:08 UTC
Labels: bug

**Comment by tinyzqh** [comment] 2023-03-30 15:58
It is work:
`pip install --upgrade setuptools==65.5.0`

**Comment by 2twentytwo2** [comment] 2023-03-30 15:58
您好，您的邮件我已收到，
看到后，我会立即回复您。
This is an automatic reply, confirming that your e-mail was received.Thank you
